# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Last.Fm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Last.Fm

    pod 'Alamofire', '~> 4.8'
    pod 'AlamofireImage', '~> 3.5.0'
    pod 'AlamofireObjectMapper', '~> 5.0'

end
